FROM  node:16
LABEL  project = "qtlearning" 
LABEL  author = "balu"
RUN git clone https://github.com/gothinkster/angular-realworld-example-app.git
RUN  cd angular-realworld-example-app
WORKDIR  /angular-realworld-example-app && npm install -g @angular/cli && npm install && npm install --legacy-peer-deps
EXPOSE  4200
CMD  ["ng","serve","--host","0.0.0.0"]
