---
apiVersion: v1
kind: Pod
metadata:
  name: config_env
spec:
  restartPolicy: OnFailure
  containers:
    - image: alpine:3
      name: alpine
      command:
        - sleep
        - 1d
      envFrom:
        - configMapRef:
            name: hai-configmap