---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
matadata: 
  name: podautoscalling
spec:
  maxReplicas: 10
  minReplicas: 2
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deploy