---
apiVersion: v1
kind: Pod
metadata:
  name: taint-tolerations
spec:
  containers:
    - image: nginx:1.23
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
  tolerations:
    - key: poc
      operator: Equal
      value: "true"