---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: resource-limits
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels: 
      app: jenkins
      version: 2.60.3
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins
        version: 2.60.3
    spec:
      containers:
        - image: jenkins/jenkins:2.60.3
          name: jenkins-container
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests: 
              memory: "64mi"
              cpu: "250m"
            limits:
              memory: "128mi"
              limits: "500m"


