---
apiVersion: v1
kind: Pod
metadata:
  name: no-restartpolicy
spec:
  containers:
    - image: alpine:3
      name: alpine-container
      command:
        - sleep
        - "2"
---
apiVersion: v1
kind: Pod
metadata:
  name: no-restartpolicy
spec:
  containers:
    - image: alpine:3
      name: alpine-container
      command:
        - sleep
        - "2"
  restartPolicy: Never
