---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
    ver: "1.0"
  ports:
    - port: 32000
      targetPort: 80
      protocol: TCP
      name: webport