---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
    ver: "1.0"
  ports:
    - nodePort: 32003
      port: 35000
      targetPort: 80
      protocol: TCP
      name: webport