---
apiVersion: v1
kind: Pod
metadata: 
  name: my-secret
spec:
  containers:
    - image: alpine:3
      name: alpine
      command:
        - sleep
        - 1d
      volumeMounts:
        - name: secrets
          mountPath: /secrets
  volumes:
    - name: secrets
      secret:
        secretName: hai-secret