---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - image: mysql:8.2
      name: mysql-pod
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: mydb
        - name: MYSQL_USER
          value: baludevops
        - name: MYSQL_PASSWORD
          value: baludevops
      volumeMounts: 
        - name: my-vol
          mountPath: /var/lib/mysql
  restartPolicy: Never
  volumes: 
    - emptyDir:
      name: my-vol

      