---
version: "3.9"
services:
  webserver:
    image: nginx:1.24
    ports:
      - target: 80
        published: 8081
        protocol: tcp
        mode: host
    networks:
      - webserver-network
  db:
    image: mysql:5.7
    ports:
      - target: 3306
        published: 8082
        protocol: tcp
        mode: host
    networks:
      - webserver-network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=directdevops
      - MYSQL_PASSWORD=directdevops
networks:
  webserver-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24