---
version: "3.9"
services:
  student-service:
    build:
      context: .
    networks:
      - student-net
      - student-privatenet
    environment:
      - MySQL_SERVER=db-service
    ports:
      - target: 8080
        published: 8081
        protocol: tcp
        mode: host
    depends_on:
      - db-service
  db-service:
    image: mysql:5.6
    networks:
      - student-privatenet
    environment:
      - MYSQL_ROOT_PASSWORD=password
        MYSQL_DATABASE=test
        MYSQL_USER=balumahendra
        MYSQL_PASSWORD=balumahendra
    volumes:
      - type: volume
        source: student-volume
        target: /var/lib/mysql
volumes:
  student-volume:
networks:
  student-net:
    driver: bridge
    ipam:
      config:
        - subnet: "192.18.0.1/24"
  student-privatenet:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.0.2/24"
    
       