---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nginx
spec:
  minReadySeconds: 3
  replicas: 5
  selector:
    app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        ver: "1.23"
    spec:
      containers:
        - image: nginx:1.23
          name: nginx-container
          ports:
            - containerPort: 80
              protocol: TCP
      