---
apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace

---
apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
  namespace: my-namespace
  labels:
    app: alpine
spec:
  backoffLimit: 6
  manualSelector: true
  selector:
    matchLabels:
      purpose: execute
  template:
    metadata:
      name: demo-job
      labels:
        purpose: execute
      namespace: my-namespace
    spec:
      containers: 
        - image: alpine:3
          name: alpine
          command: 
            - sleep
            - 60s
          restartPolicy: Never

