
---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: jenkins
  labels:
    app: cicd
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      name: jenkins-replicas
      labels:
        app: cicd
    spec:
      initContainers:
        - image: alpine:3
          name: alpine-container
          command: ["ping","-c","4","google.com"]
      containers:
        - image: jenkins/jenkins:2.60.3
          name: jenkins
          ports:
            - containerPort: 8080
              protocol: TCP